package main

import (
	"context"
	"fmt"
	"go/format"
	"os"
	"slices"
	"strings"

	"github.com/nexthop-ai/openpsirt/internal/database"
)

// Asking the engines what they reserve, rather than trusting a list.
//
// An engine upgrade adds reserved words — MySQL and MariaDB both do, across
// minor releases — and a check against a committed list keeps passing while a
// query inventing that alias fails as a syntax error on whichever engine a
// deployment happens to run. Asking the engines is what stops the list drifting
// from what they enforce.
//
// **Two of the four are asked and two are typed**, which is stated here and in
// the generated file rather than glossed:
//
//   - PostgreSQL publishes pg_get_keywords(). Asked.
//   - MySQL publishes INFORMATION_SCHEMA.KEYWORDS. Asked.
//   - MariaDB publishes no keywords table at all. The words it reserves that
//     MySQL does not are typed, from its own documentation, and that is a gap.
//   - SQLite publishes its keyword list only through a C entry point, which
//     from here means the driver's own translation of libsqlite3 rather than
//     anything reachable over SQL. Its words are typed, from its documentation.
//
// Asking SQLite indirectly does not work: it accepts most of its own keywords
// as an alias, so putting each back as "SELECT 1 AS word" reports nearly all of
// them as unreserved. The list here is wider than what any one engine rejects —
// it is what is reserved on *any* of the four — so that probe answers a
// different question.

// generateURLEnv names where the generator finds each engine it asks. The same
// variables the test harness reads, so "make engines-up" configures both.
var generateURLEnv = map[database.Engine]string{
	database.Postgres: "OPENPSIRT_TEST_POSTGRES_URL",
	database.MySQL:    "OPENPSIRT_TEST_MYSQL_URL",
}

// askEngines is the reserved words PostgreSQL and MySQL name for themselves.
func askEngines(ctx context.Context) ([]string, error) {
	queries := map[database.Engine]string{
		// Reserved, and reserved-except-as-a-function-or-type: both are words
		// this cannot use bare as an alias.
		database.Postgres: `SELECT "word" FROM pg_get_keywords() WHERE "catcode" IN ('R', 'T')`,
		database.MySQL:    `SELECT LOWER("WORD") FROM "INFORMATION_SCHEMA"."KEYWORDS" WHERE "RESERVED" = 1`,
	}
	found := map[string]bool{}
	for _, engine := range database.Engines() {
		query, asked := queries[engine]
		if !asked {
			continue
		}
		url := os.Getenv(generateURLEnv[engine])
		if url == "" {
			return nil, fmt.Errorf("%s is unset, so %s could not be asked what it "+
				"reserves: run make engines-up", generateURLEnv[engine], engine)
		}
		words, err := wordsFrom(ctx, url, query)
		if err != nil {
			return nil, fmt.Errorf("ask %s what it reserves: %w", engine, err)
		}
		if len(words) == 0 {
			return nil, fmt.Errorf("%s named no reserved words, so this generated nothing", engine)
		}
		for _, word := range words {
			found[word] = true
		}
	}
	out := make([]string, 0, len(found))
	for word := range found {
		out = append(out, word)
	}
	slices.Sort(out)
	return out, nil
}

func wordsFrom(ctx context.Context, url, query string) ([]string, error) {
	target, err := database.ParseURL(url)
	if err != nil {
		return nil, err
	}
	db, err := database.Open(ctx, target)
	if err != nil {
		return nil, fmt.Errorf("open %s: %w", target.Redacted, err)
	}
	defer func() { _ = db.Close() }()
	rows, err := db.QueryContext(ctx, query)
	if err != nil {
		return nil, err
	}
	defer func() { _ = rows.Close() }()
	var words []string
	for rows.Next() {
		var word string
		if err := rows.Scan(&word); err != nil {
			return nil, err
		}
		words = append(words, strings.ToLower(strings.TrimSpace(word)))
	}
	return words, rows.Err()
}

// writeGenerated renders the asked half of the list as Go.
func writeGenerated(path string, words []string) error {
	var out strings.Builder
	out.WriteString(`// Code generated by "make reserved-words". DO NOT EDIT.

package main

// askedWords is what PostgreSQL and MySQL answered when asked what they
// reserve. Regenerating against a newer engine is how a word either of them
// adds arrives here.
//
`)
	fmt.Fprintf(&out, "// %d words. Sorted, so a regeneration is a diff somebody can read.\n", len(words))
	out.WriteString("var askedWords = []string{\n")
	for i, word := range words {
		if i%6 == 0 {
			out.WriteString("\t")
		}
		fmt.Fprintf(&out, "%q,", word)
		if i%6 == 5 || i == len(words)-1 {
			out.WriteString("\n")
		} else {
			out.WriteString(" ")
		}
	}
	out.WriteString("}\n")
	body, err := format.Source([]byte(out.String()))
	if err != nil {
		return fmt.Errorf("format the generated list: %w", err)
	}
	return os.WriteFile(path, body, 0o600)
}

// generate rewrites the asked half of the word list and reports what moved.
func generate() error {
	asked, err := askEngines(context.Background())
	if err != nil {
		return err
	}
	was := reservedWords()
	if err := writeGenerated("internal/tools/reserved/words_asked.go", asked); err != nil {
		return err
	}
	fmt.Printf("asked PostgreSQL and MySQL what they reserve: %d words, "+
		"beside %d typed for SQLite and %d for MariaDB\n",
		len(asked), len(sqliteWords), len(mariadbWords))
	for _, word := range asked {
		if !slices.Contains(was, word) {
			fmt.Printf("  added   %s\n", word)
		}
	}
	for _, word := range was {
		if !slices.Contains(asked, word) &&
			!slices.Contains(sqliteWords, word) && !slices.Contains(mariadbWords, word) {
			fmt.Printf("  removed %s\n", word)
		}
	}
	return nil
}
