package main

// reservedWords is every word that is reserved on at least one of the four
// engines this runs against, so an invented alias spelled as one of them is a
// query that parses here and fails there.
//
// Regenerated by "make reserved-words", which asks the running engines rather
// than trusting a list somebody typed:
//
//   - PostgreSQL 16: pg_get_keywords(), the reserved and type-name categories.
//   - MySQL 8.4: INFORMATION_SCHEMA.KEYWORDS where RESERVED = 1.
//   - MariaDB 11.4: no KEYWORDS table, so the words it reserves that MySQL
//     does not are listed by hand from its documentation. The rest of its
//     list is MySQL's.
//   - SQLite: its keyword list, of which only these are not already above.
//
// 321 words. Sorted, so a regeneration is a diff somebody can read.
var reservedWords = []string{
	"abort", "accessible", "add", "all", "alter", "analyse",
	"analyze", "and", "any", "array", "as", "asc",
	"asensitive", "asymmetric", "attach", "authorization", "autoincrement", "before",
	"between", "bigint", "binary", "blob", "both", "by",
	"call", "cascade", "case", "cast", "change", "char",
	"character", "check", "collate", "collation", "column", "concurrently",
	"condition", "conflict", "constraint", "continue", "convert", "create",
	"cross", "cube", "cume_dist", "current_catalog", "current_date", "current_role",
	"current_schema", "current_time", "current_timestamp", "current_user", "cursor", "database",
	"databases", "day_hour", "day_microsecond", "day_minute", "day_second", "dec",
	"decimal", "declare", "default", "deferrable", "delayed", "delete",
	"delete_domain_id", "dense_rank", "desc", "describe", "detach", "deterministic",
	"distinct", "distinctrow", "div", "do", "do_domain_ids", "double",
	"drop", "dual", "each", "else", "elseif", "empty",
	"enclosed", "end", "escaped", "except", "exists", "exit",
	"explain", "false", "fetch", "first_value", "float", "float4",
	"float8", "for", "force", "foreign", "freeze", "from",
	"full", "fulltext", "function", "general", "generated", "get",
	"glob", "grant", "group", "grouping", "groups", "having",
	"high_priority", "hour_microsecond", "hour_minute", "hour_second", "if", "ignore",
	"ignore_domain_ids", "ignore_server_ids", "ilike", "in", "index", "indexed",
	"infile", "initially", "inner", "inout", "insensitive", "insert",
	"instead", "int", "int1", "int2", "int3", "int4",
	"int8", "integer", "intersect", "interval", "into", "io_after_gtids",
	"io_before_gtids", "is", "isnull", "iterate", "join", "json_table",
	"key", "keys", "kill", "lag", "last_value", "lateral",
	"lead", "leading", "leave", "left", "like", "limit",
	"linear", "lines", "load", "localtime", "localtimestamp", "lock",
	"long", "longblob", "longtext", "loop", "low_priority", "master_heartbeat_period",
	"match", "maxvalue", "mediumblob", "mediumint", "mediumtext", "middleint",
	"minute_microsecond", "minute_second", "mod", "modifies", "natural", "no_write_to_binlog",
	"not", "notnull", "nth_value", "ntile", "null", "numeric",
	"of", "offset", "on", "only", "optimize", "optimizer_costs",
	"option", "optionally", "or", "order", "out", "outer",
	"outfile", "over", "overlaps", "page_checksum", "parse_vcol_expr", "partition",
	"percent_rank", "placing", "position", "pragma", "precision", "primary",
	"procedure", "purge", "qualify", "range", "rank", "read",
	"read_write", "reads", "real", "recursive", "ref_system_id", "references",
	"regexp", "reindex", "release", "rename", "repeat", "replace",
	"require", "resignal", "restrict", "return", "returning", "revoke",
	"right", "rlike", "row", "row_number", "rows", "schema",
	"schemas", "second_microsecond", "select", "sensitive", "separator", "session_user",
	"set", "show", "signal", "similar", "slow", "smallint",
	"some", "spatial", "specific", "sql", "sql_big_result", "sql_calc_found_rows",
	"sql_small_result", "sqlexception", "sqlstate", "sqlwarning", "ssl", "starting",
	"stats_auto_recalc", "stats_persistent", "stats_sample_pages", "stored", "straight_join", "symmetric",
	"system", "system_user", "table", "tablesample", "temp", "terminated",
	"then", "tinyblob", "tinyint", "tinytext", "to", "trailing",
	"trigger", "true", "undo", "union", "unique", "unlock",
	"unsigned", "update", "usage", "use", "user", "using",
	"utc_date", "utc_time", "utc_timestamp", "vacuum", "values", "varbinary",
	"varchar", "varcharacter", "variadic", "varying", "verbose", "virtual",
	"when", "where", "while", "window", "with", "write",
	"xor", "year_month", "zerofill",
}
