{{- if and .Values.database.url (not .Values.database.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openpsirt.fullname" . }}-database
  labels: {{- include "openpsirt.labels" . | nindent 4 }}
type: Opaque
stringData:
  database-url: {{ .Values.database.url | quote }}
{{- end }}
{{- if and .Values.auth.oidc.clientSecret (not .Values.auth.oidc.existingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openpsirt.fullname" . }}-oidc
  labels: {{- include "openpsirt.labels" . | nindent 4 }}
type: Opaque
stringData:
  oidc-client-secret: {{ .Values.auth.oidc.clientSecret | quote }}
{{- end }}
{{- if and .Values.auth.github.clientSecret (not .Values.auth.github.existingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openpsirt.fullname" . }}-github
  labels: {{- include "openpsirt.labels" . | nindent 4 }}
type: Opaque
stringData:
  github-client-secret: {{ .Values.auth.github.clientSecret | quote }}
{{- end }}
{{- if and .Values.mail.password (not .Values.mail.existingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openpsirt.fullname" . }}-mail
  labels: {{- include "openpsirt.labels" . | nindent 4 }}
type: Opaque
stringData:
  mail-password: {{ .Values.mail.password | quote }}
{{- end }}
